language: r
r:
  - devel
dist: bionic
cache: packages
warnings_are_errors: false
latex: false

# install debian libraries to match R-servers
# update pre-installed packages to latest versions
before_install:
  - export R_REMOTES_NO_ERRORS_FROM_WARNINGS="true"
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get install -y libgdal-dev libproj-dev python-protobuf libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev
  - sudo add-apt-repository -y ppa:cran/libgit2
  - sudo apt-get -qq update
  - sudo apt-get install libgit2-dev
  - mkdir -p ~/.R/
  - echo "CXXFLAGS = `R CMD config CXXFLAGS` -g0 -flto -w" >> ~/.R/Makevars
  - echo "CXX14FLAGS = -w -O3" >> ~/.R/Makevars
  - sudo apt-get install -y r-cran-rcppeigen
  - Rscript tools/travis_run_before_install.R

r_packages:
  - devtools
  - roxygen2

r_github_packages:
  - Displayr/flipDevTools
  - Displayr/flipExampleData

script:
  - R CMD build --no-manual --no-build-vignettes --no-resave-data .
  - R CMD check --as-cran --no-manual --no-build-vignettes --no-tests *.tar.gz
  - travis_wait 40 ./runTravisTests.sh
notifications:
  slack:
    rooms:
      - displayr:FTgSTNHC2rpanhJMGTKMwZXM#github-notifications
    template:
      - "Build <%{build_url}|#%{build_number}> %{result} in %{repository_name}@%{branch} by %{author}: <%{compare_url}|%{commit_message}>"
    on_success: change
    on_failure: always

# Warning notifications and downstream package builds are implemented
# by calling R functions so they can be updated in this package without
# committing a new change to .travis.yml in each repository
after_success:
  - Rscript -e "require(flipDevTools); NotifyWarnings(); TriggerDownstreamBuilds()"
