## tic Circle CI template: linux-deploy
## revision date: 2022-08-28
version: 2.1
jobs:
  r-release:
    docker:
      - image: rocker/tidyverse:latest
        auth:
          username: mwmclean
          password: $DOCKERHUB_PAT

    steps:
      - checkout

      # create a unique env var for the cache. Unfortunately normal env vars
      # are not picked up by the cache, therefore this workaround is needed.
      # See https://discuss.circleci.com/t/cannot-use-circle-yml-environment-variables-in-cache-keys/10994/7
      - run: echo "$(Rscript -e 'cat(format(getRversion()))')" > /tmp/R_version
      - restore_cache:
          key: R-package-library-{{ checksum "/tmp/R_version" }}

      # install deps and check pkg ---------------------------------------------
      - run:
          name: "[r-release] Install dependencies"
          command: |
            sudo apt update && sudo apt install -y ccache pandoc libgit2-dev libharfbuzz-dev libfribidi-dev libprotoc-dev libprotobuf-dev libv8-dev librsvg2-dev libmpfr-dev libnlopt-dev
            R -q -e 'if (!dir.exists("~/R/library")) dir.create("~/R/library", recursive = TRUE)'
            echo -e 'options(Ncpus = 4, repos = structure(c(CRAN = "https://cloud.r-project.org/")))' > $HOME/.Rprofile
            echo -e '.libPaths("~/R/library")' >> $HOME/.Rprofile
            R -q -e 'devtools::install_deps(dependencies = TRUE)'

      - run:
          name: "Check package"
          command: R -q -e 'rcmdcheck::rcmdcheck(args = c("--no-manual", "--ignore-vignettes", "--no-tests"), build_args = c("--no-build-vignettes"))'

      - run:
          name: "Run unit tests"
          command: >-
              R -e 'capture.output(out \<<- devtools::test(reporter = "junit"), file = "test_output.txt");
              results <- unlist(lapply(out, `[[`, "results"), recursive = FALSE);
              output <- readLines("test_output.txt");
              writeLines(output[grep("^[<][?]xml", output)[1L]:length(output)], "testthat.xml");
              q(status = as.integer(!all(vapply(results, function(res) class(res)[1], "") %in%
              c("expectation_success", "expectation_skip"))), save = "no")'

      - store_test_results:
          path: testthat.xml

      # save R pkg cache -------------------------------------------------------
      - save_cache:
          key: R-package-library-{{ checksum "/tmp/R_version" }}
          paths:
            - R/library

workflows:
  build-and-check-R-package:
    jobs:
      - r-release
